apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude

resources:
  - ../../base
  - ingress.yml

images:
  - name: ghcr.io/asseris-asi/claude-usage-dashboard
    newTag: latest
